### ISSUE TITLE
Workers ready for work again

### ISSUE THREAD

**Issue by lookingcloudy** [nesv/nesv.github.io#10]
Nice article!

Seems to me that once the dispatcher pulls a Worker from the WorkerQueue, that Worker never adds itself back to the WorkerQueue when it is ready for work again and therefore is a once-and-done worker, but still running.

Also, when the app shuts down, how can it make sure all the workers are finished processing prior to shutting down?

**Comment by lookingcloudy** [comment]
Oops - never mind...just saw where the worker was adding itself in!

**Comment by nesv** [comment]
Hey, @lookingcloudy. 

In `worker.go` on line 35 (at the top of the `for` loop), the worker adds itself back into the WorkerQueue.

As for shutting down, I didn't think of that at the time I wrote the article. At a glance, one could probably use multiple `sync.WaitGroup`s:
- One in `main.go` for guarding the dispatcher
- Another in the dispatcher for guarding the workers (this might require implementing the dispatcher as a struct depending on how it is approached)

...as well as a way to signal a shutdown request from the `main()` function to the dispatcher. Once the dispatcher receives the shutdown signal, it would loop through each of the workers, calling their `Stop()` method. Each time a worker is stopped, it would call the dispatcher's `sync.WaitGroup`'s `Done()` method, where the dispatcher would be held on `(*WaitGroup).Wait()`.

Edit: I'm glad you found it! That will teach me to type faster.
