### ISSUE TITLE
Question about the post 'Writing worker queues, in Go'

### ISSUE THREAD

**Issue by lazybetrayer** [nesv/nesv.github.io#3]
http://nesv.github.io/golang/2014/02/25/worker-queues-in-go.html
Great article. But I have a stupid question. What's the difference with getting rid of the dispatcher and having all workers pull work requests from work queue directly?

**Comment by nesv** [comment]
I am glad you enjoyed it! :smile: 

Funny enough, someone else asked this same question on Reddit, to [which I responded](http://www.reddit.com/r/golang/comments/1z0ag0/writing_worker_queues_in_go/cftse7f). 

The only reason for the dispatcher is "personal preference"; having a central control point makes it easier (in my opinion) to debug, and extend.

**Comment by lazybetrayer** [comment]
I understand now. Thanks.
