### ISSUE TITLE
Typo in Code Example

### ISSUE THREAD

**Issue by mcnamarabrian** [nesv/nesv.github.io#4]
Thanks so much for sharing your example, @nesv.  I'm just getting started with Go and have been looking for a mall project to hack on and your work on the Dyn client is a big help.

I found one minor typo in the code example listed at http://nesv.github.io/golang/dynect/dns/2014/05/15/go-dynect.html.  I believe line 36 should be zonesResponse.Data.

**Comment by nesv** [comment]
You are absolutely correct! Thank you for spotting that!

**Comment by nesv** [comment]
It has been fixed. Thank you, again.
