### ISSUE TITLE
'Worker queues in Go' - WorkerQueue chan

### ISSUE THREAD

**Issue by mikeys** [nesv/nesv.github.io#7]
@nesv 
Hey there Nick,
Just went through your great article: http://nesv.github.io/golang/2014/02/25/worker-queues-in-go.html
Was wondering though, since I've this quite a few times already in various tutorials and talks about Go:
Why do we need this extra `WorkerQueue chan chan WorkRequest` which the Workers need to send down their channel so the dispatcher will know that they're free?
Why aren't you simply using a single `WorkRequestQueue chan` and passing it as a param when creating the workers and when a `WorkRequest` comes up into the Dispatcher, it simply sends it down the `WorkRequestQueue chan`? As soon as one of the workers gets freed up, it will simply fetch that Job instance from that single `WorkRequestQueue chan`and start processing it, since AFAIK when you send a message through a channel, only one receiver will fetch it... Am I missing something here? Why does each worker needs to have it's own request chan?

**Comment by nesv** [comment]
Hey @mikeys,

No, you're not missing anything. The reason I opted for a `chan chan WorkRequest`, was simply because it seemed cleaner at the time. No special reason. I'm sure passing the `chan WorkRequest` into each `Worker` would work just fine.

Also, I'm glad you enjoyed the article. :smile:

**Comment by mikeys** [comment]
@nesv Got it, thanks for the response :smile:

**Comment by cobblau** [comment]
Hi @nesv, 
Thanks for your great article http://nesv.github.io/golang/2014/02/25/worker-queues-in-go.html. I'v learned much after reading it. 
Could you please post the source code mentioned in this article?

Thank you very much.

**Comment by nesv** [comment]
@cobblau The source code is in the article. Are you not able to see it?
