### ISSUE TITLE
About the worker pool post

### ISSUE THREAD

**Issue by eullerpereira94** [nesv/nesv.github.io#8]
Hi, I know that maybe this isn't the place to talk about your blog post, but there's some things I want to say to you.

I basically copied the code you provide, but I also made some minor modifications to adjust my needs. The first one is that the application is not a web server, but rather a file parser. The second is that, after the file is parsed, I want application to finishes, rather than waiting for more work.

The reason for the need of a worker pool is, since the file can be really big, and the result of the parsing of one file line doesn't affects the others, I can divide the load between a number of workers to reduce the wait for the results.

The problem is, everything works fine but, after the file is parsed, the workers don't  stop and keep waiting for more jobs. This prevents the application to finishes after the parsing, forcing me to kill the application manually.

I can't figure out a way to make the workers stop automatically, thus also making the application to stop automatically too, so can you help me out with this?

**Comment by nesv** [comment]
Hi @euller88! 

So, while I am more than willing to help you with this, for this kind of processing, you might find a package like [glow](https://github.com/chrislusf/glow) to be a more suited to what you're trying to do.

In either case, there are several things in the examples in my blog post that should probably be fixed: the `Worker.Start()` and `Worker.Stop()` methods should be have a pointer receiver: 

``` go
func (w *Worker) Start() {
        ....
}

func (w *Worker) Stop() {
        ...
}
```

Secondly, are you calling the `Worker.Stop()` method, and is it failing to stop the worker? If so, the above changes should fix that.

As for performing a batch job like this, you should probably use a `sync.WaitGroup`. This will require you to restructure the application a little bit, though. First, declare a `sync.WaitGroup`:

``` go
var wg sync.WaitGroup
```

Then, every time a new worker is started, call `wg.Add(1)`, and pass the `sync.WaitGroup` into the `NewWorker()` function. Each `Worker` should have a field that can store the `sync.WaitGroup`. That way, each `Worker` has a reference to the `sync.WaitGroup`, and can call `wg.Done()` when it has been stopped. For example:

``` go
func NewWorker(id int, workerQueue chan chan WorkRequest, wg *sync.WaitGroup) Worker {
  worker := Worker{
    ID:          id,
    Work:        make(chan WorkRequest),
    WorkerQueue: workerQueue,
    QuitChan:    make(chan bool),
    wg: wg,
}

  return worker
}

type Worker struct {
  ID          int
  Work        chan WorkRequest
  WorkerQueue chan chan WorkRequest
  QuitChan    chan bool
  wg *sync.WaitGroup
}

func (w *Worker) Start() {
    go func() {
      for {
        // Add ourselves into the worker queue.
        w.WorkerQueue <- w.Work

        select {
        case work := <-w.Work:
          // Receive a work request.
          fmt.Printf("worker%d: Received work request, delaying for %f seconds\n", w.ID, work.Delay.Seconds())

          time.Sleep(work.Delay)
          fmt.Printf("worker%d: Hello, %s!\n", w.ID, work.Name)

        case <-w.QuitChan:
          // We have been asked to stop.
          fmt.Printf("worker%d stopping\n", w.ID)
          w.wg.Done()
          return
        }
      }
    }()
}
```

In the `StartDispatcher()` function, remove the `go func() { ... }` wrapping around the second `for` loop, and after that second `for` loop, put the line `wg.Wait()`. This will cause the `StartDispatcher()` function to wait until all of the workers have finished, before returning.

**EDIT** Again, I would _really_ recommend you take a peek at the [glow](https://github.com/chrislusf/glow) package.

**Comment by eullerpereira94** [comment]
Thank you for your answer, it's really helpful. Keep up with the good work.
