### ISSUE TITLE
Stopping the workers?

### ISSUE THREAD

**Issue by AHaymond** [nesv/nesv.github.io#9]
How would one go about stopping the workers as the work queue dries up?

**Comment by nesv** [comment]
The `Worker` struct has a `Stop()` method, which would signal the worker to exit its internal loop and therefore prevent the worker from re-submitting itself into the worker queue. However, simply extending the example implementation in the blog post would probably be a large headache.

If you are concerned about resources and not wanting to have N-workers just waiting around for work to do, I would recommend implementing a [semaphore](http://www.golangpatterns.info/concurrency/semaphores). My thinking on this approach goes something like this:
- A work request comes in from the collector (the HTTP endpoint), and is sent to the dispatcher
- The dispatcher instantiates a worker to handle a work request
- When a worker starts up, it adds itself to the worker queue (`w.WorkerQueue <- w.Work`)
- The worker has no internal `for` loop; the worker will rely on the channel read operation to block
- When the worker is done its work, it will simply exit and cease to exist

Using a semaphore (like the one in the above link), you can guarantee that you will never have more than _N_ workers at any given time, and every time a work request is received by the dispatcher, it will just blindly spin up a new worker or block until `num_workers < N`. As the work queue dries up, you will have 0 (zero) idle workers.

I hope that helps. :)
